# Generated by Django 5.2.7 on 2026-08-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="categorie",
            new_name="category",
        ),
    ]
