# Generated by Django 5.2.7 on 2026-08-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
