# Generated by Django 5.2.7 on 2026-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_borrowing_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
