"""
Django settings for library_management_system project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/



ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "core",
    "books",
    "borrowing",
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "library_management_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "library_management_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



MEDIA_URL = '/media/' ## This is the URL that will be used to access media files in the browser. For example, if you have an image file named "example.jpg" in your media directory, you can access it at http://yourdomain.com/media/example.jpg.
MEDIA_ROOT = BASE_DIR / 'media' # in main project directory or base directory, we will create a folder named media where all the uploaded media files will be stored. This is the absolute filesystem path to the directory where Django will store uploaded files.



import environ
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')  ## This line reads the .env file and loads the environment variables


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY') ## This is the secret key that Django uses for cryptographic signing. It is retrieved from the .env file, where you have stored it as an environment variable. This is a security measure to keep sensitive information like the secret key out of the source code and version control.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG') ## This line retrieves the DEBUG setting from the .env file.

## For sending Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = env('EMAIL_USER') ## This is the email address that will be used as the sender of the email. It is retrieved from the Django settings file, where you have configured your email backend and provided the email address to be used for sending emails.
EMAIL_HOST_PASSWORD = env('EMAIL_PASSWORD') ## This is the password for the email account specified in EMAIL_HOST_USER. It is also retrieved from the Django settings file, where you have configured your email backend and provided the password for the email account.
# in .env file element we access env('in_env_file_variable_name') and we can use this variable in our code, so we can keep our sensitive information like email password in .env file and we can access it in our code using env('in_env_file_variable_name').
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


## FOR USING @login_required decorator  & LoginRequiredMixin
LOGIN_URL = "user_login" # ## This is the URL where users will be redirected if they try to access a view that requires authentication and they are not logged in. In this case, it is set to the URL pattern named "user_login", which should correspond to the login page of your application.







DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env('DB_USER'),
        "PASSWORD": env('DB_PASS'),
        "HOST": env('DB_HOST'  ),
        "PORT": env('DB_PORT'),
    }
}
